services:
  db:
    image: postgres:alpine
    user: postgres
    restart: always
    expose:
      - "5432"
    volumes:
      - ./db/housemate.sql:/docker-entrypoint-initdb.d/base.sql
    environment:
      - POSTGRES_PASSWORD=password

  backend:
    build: backend
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - POSTGRES_HOST=db

  frontend:
    build: frontend
    ports:
      - "127.0.0.1:3000:3000"
